# Generated by Django 5.1.4 on 2024-12-06 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinatesX', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='The X Coordinate')),
                ('coordinatesY', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='The Y Cordinate')),
                ('lastUpdated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainName', models.CharField(max_length=100)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.location')),
            ],
        ),
    ]
