# Generated by Django 5.1.4 on 2024-12-06 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seatSize', models.IntegerField()),
                ('open', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='CouchType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seatCapacity', models.IntegerField()),
                ('seatPrice', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AVL', 'Available'), ('RES', 'Reserved'), ('BKL', 'Booked')], default='RES', max_length=3)),
            ],
        ),
        migrations.AlterField(
            model_name='location',
            name='lastUpdated',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated'),
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seatSize', models.IntegerField()),
                ('couch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reservations.cabin')),
            ],
        ),
        migrations.CreateModel(
            name='Couch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('cabinSize', models.IntegerField()),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.train')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.couchtype')),
            ],
        ),
        migrations.AddField(
            model_name='cabin',
            name='couch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.couch'),
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stationName', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=30)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.location')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrivalTime', models.TimeField()),
                ('departureTime', models.TimeField()),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.train')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.station')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distanceToDestination', models.IntegerField()),
                ('travelTime', models.TimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.location')),
                ('destinationStation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinationStation_set', to='reservations.station')),
                ('sourceStation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soureceStation_set', to='reservations.station')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seatNumber', models.IntegerField()),
                ('inACabin', models.BooleanField()),
                ('cabin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.cabin')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.column')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.status')),
            ],
        ),
        migrations.CreateModel(
            name='UserBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.schedule')),
            ],
        ),
    ]
