# Generated by Django 5.1.4 on 2024-12-06 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_cabin_couchtype_status_alter_location_lastupdated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reservations.location'),
        ),
    ]
