# Generated by Django 5.1.4 on 2024-12-06 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_alter_train_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='couch',
            old_name='name',
            new_name='code',
        ),
    ]
