# Generated by Django 5.1.4 on 2024-12-06 12:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_rename_name_couch_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='couchtype',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='couch',
            name='code',
            field=models.CharField(editable=False, max_length=5),
        ),
    ]
