# Generated by Django 5.1.4 on 2024-12-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_couchtype_name_alter_couch_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabin',
            name='code',
            field=models.CharField(default='code', editable=False, max_length=1),
            preserve_default=False,
        ),
    ]
