# Generated by Django 5.1.4 on 2024-12-07 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_userbooking_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='station',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reservations.location'),
        ),
        migrations.AlterField(
            model_name='station',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.city', unique=True),
        ),
    ]
