# Generated by Django 5.1.4 on 2024-12-07 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_city_alter_station_location_alter_station_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.city'),
        ),
    ]
