# Generated by Django 5.1.4 on 2024-12-07 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0010_alter_station_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='station',
        ),
        migrations.AddField(
            model_name='schedule',
            name='route',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reservations.route'),
        ),
    ]
