# Generated by Django 5.1.4 on 2024-12-07 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0011_remove_schedule_station_schedule_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='route',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='reservations.route'),
        ),
    ]
