# Generated by Django 5.1.4 on 2024-12-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0013_alter_schedule_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='travelTime',
            field=models.TimeField(),
        ),
    ]
