# Generated by Django 5.1.4 on 2024-12-07 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0014_alter_route_traveltime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='travelTime',
        ),
    ]
