# Generated by Django 5.1.4 on 2024-12-07 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0015_remove_route_traveltime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='cabin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservations.cabin'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='column',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservations.column'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='inACabin',
            field=models.BooleanField(default=True),
        ),
    ]
