# Generated by Django 5.1.4 on 2024-12-07 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0016_alter_seat_cabin_alter_seat_column_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabin',
            name='code',
            field=models.CharField(editable=False, max_length=1, null=True),
        ),
    ]
