# Generated by Django 5.1.4 on 2024-12-07 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0017_alter_cabin_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabin',
            name='seatSize',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Berth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.cabin')),
            ],
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.status')),
                ('Berth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.berth')),
            ],
        ),
    ]
