# Generated by Django 5.1.4 on 2024-12-07 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0018_alter_cabin_seatsize_berth_bed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berth',
            name='cabin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reservations.cabin'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='seatNumber',
            field=models.IntegerField(null=True),
        ),
    ]
