# Generated by Django 5.1.4 on 2024-12-07 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0019_alter_berth_cabin_alter_seat_seatnumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bed',
            old_name='Berth',
            new_name='berth',
        ),
        migrations.AlterField(
            model_name='column',
            name='couch',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reservations.couch'),
        ),
    ]
