# Generated by Django 5.1.4 on 2024-12-09 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0020_rename_berth_bed_berth_alter_column_couch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbooking',
            name='data',
        ),
        migrations.AddField(
            model_name='berth',
            name='code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='couch',
            name='code',
            field=models.CharField(editable=False, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('AVL', 'Available'), ('RES', 'Reserved'), ('BKL', 'Booked')], default='AVL', max_length=3),
        ),
    ]
