# Generated by Django 5.1.4 on 2024-12-09 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0021_remove_userbooking_data_berth_code_alter_couch_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='bedNumber',
            field=models.IntegerField(max_length=4, null=True),
        ),
    ]
