# Generated by Django 5.1.4 on 2024-12-09 23:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0022_bed_bednumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbooking',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userbooking',
            name='seat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reservations.seat'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bed',
            name='bedNumber',
            field=models.IntegerField(null=True),
        ),
    ]
