# Generated by Django 5.1.4 on 2024-12-10 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0024_couchtype_price_userbooking_berth_userbooking_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbooking',
            name='cost',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='secondary_Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrivalTime', models.TimeField()),
                ('departureTime', models.TimeField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.route')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.train')),
            ],
        ),
    ]
