# Generated by Django 5.1.4 on 2024-12-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0025_userbooking_cost_secondary_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couch',
            name='cabinSize',
            field=models.IntegerField(null=True),
        ),
    ]
