# Generated by Django 5.1.4 on 2024-12-10 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0026_alter_couch_cabinsize'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='copyTrain',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='copyTrain', to='reservations.train'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train', to='reservations.train'),
        ),
    ]
