# Generated by Django 5.1.4 on 2024-12-10 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0027_schedule_copytrain_alter_schedule_train'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.location'),
        ),
    ]
