# Generated by Django 5.1.4 on 2024-12-10 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0028_alter_train_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='father',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
