# Generated by Django 5.1.4 on 2024-12-10 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0029_train_father'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbooking',
            name='berth',
        ),
        migrations.AddField(
            model_name='userbooking',
            name='bed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reservations.bed'),
        ),
        migrations.AlterField(
            model_name='userbooking',
            name='seat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reservations.seat'),
        ),
    ]
