# Generated by Django 5.1.4 on 2024-12-13 07:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0030_remove_userbooking_berth_userbooking_bed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbooking',
            name='onData',
            field=models.DateField(default=datetime.datetime(2024, 12, 13, 7, 18, 3, 507875, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
